imports:
    - { resource: '@BeHappySyliusRightsManagementPlugin/Resources/config/right_management/catalogue.yaml' }
    - { resource: '@BeHappySyliusRightsManagementPlugin/Resources/config/right_management/customer.yaml' }
    - { resource: '@BeHappySyliusRightsManagementPlugin/Resources/config/right_management/sale.yaml' }
    - { resource: '@BeHappySyliusRightsManagementPlugin/Resources/config/right_management/marketing.yaml' }
    - { resource: '@BeHappySyliusRightsManagementPlugin/Resources/config/right_management/configuration.yaml' }

be_happy_sylius_rights_management:
    rights:
        right_management:
            all:
                name: 'be_happy_rights_management.rights.admin_group.all'
                routes: ['be_happy_rights_management_admin_group_*']
                redirect_to: sylius_admin_dashboard
                redirect_message: "be_happy_rights_management.message.access_denied"