BeHappy\SyliusRightsManagementPlugin\Entity\Right:
    type: mappedSuperclass
    table: bhc_right_right
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        name:
            type: string
        routes:
            type: json_array
        exclude:
            type: json_array
        granted:
            type: boolean
        redirectTo:
            type: string
            column: redirect_to
        redirectMessage:
            type: string
            column: redirect_message
    manyToOne:
        group:
            targetEntity: BeHappy\SyliusRightsManagementPlugin\Entity\Group
            inversedBy: rights